version: '3.8'

services:
  aerolux-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerolux-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - aerolux-network

networks:
  aerolux-network:
    driver: bridge
